Repository InkuA-Pasantia/Proyecto-web-educativa, pull requests merged in 2023-10, with the labels that each got.

#40 Poniendo en marcha el inicio de sesión de los usuarios registrados
  Backend/PRUEBAS/Inicio_Prueba_Creacion_de_usuario.png
  Backend/PRUEBAS/Inicio_sesion_DB.png
  Backend/PRUEBAS/Inicio_sesion_cookie .png
  Backend/database/init.sql
  Backend/src/controller/auth.controller.js
  Backend/src/libs/jwt.js
  Backend/src/middlewares/auth.middleware.js
  Backend/src/router/cursos.routes.js
Labels: JavaScript

#43 Agrego código para el signout y captura pantalla de cierre de sesión.
  Backend/PRUEBAS/prueba_signout_usuario.jpg
  Backend/src/controller/auth.controller.js
Labels: enhancement

#50 Relaciono cursos con usuarios y mail con gravatar
  Backend/database/init.sql
  Backend/src/controller/auth.controller.js
  Backend/src/controller/cursos.controller.js
  package-lock.json
Labels: enhancement

#61 Formulario de registro Parte 1
  Backend/frontend/src/components/ui/Button.jsx
  Backend/frontend/src/components/ui/Card.jsx
  Backend/frontend/src/components/ui/Input.jsx
  Backend/frontend/src/pages/RegisterPage.jsx
  package-lock.json
Labels: JavaScript

#86 IA_Chat_Bot - Actualización
  Backend/IA_Chat_Bot/images/chatbot.jpg
  Backend/IA_Chat_Bot/images/user.jpg
  Backend/IA_Chat_Bot/img/chatgpt_logo.jpeg
  Backend/IA_Chat_Bot/index.html
  Backend/IA_Chat_Bot/script.js
  Backend/IA_Chat_Bot/style.css
Labels: JavaScript, HTML, CSS
